#include "fogml_helper.h"

#include <stdint.h>
#include <math.h>

/*float pow2f(float a) {
	return a*a;
}*/

static int C() { int c; asm volatile ("rdcycle %0" : "=r"(c)); return c; }

uint32_t float_square_bitlevel(uint32_t x, int* c) {
    if (x == 0)
        return x;

	// keep the exponent in high 8-bits, subtract bias
	// and the fraction and add implicit 1
    uint32_t exp =  ((x<<1) & 0xFF000000) - 0x7F000000;
    uint64_t frac =  (x & 0x007FFFFF) | 0x00800000;
    
    // double the exponent and add back the bias without
    // squared fraction power
    exp *= 2;
    exp += 0x68000000; // 0x7F (bias) - 23 (squared fixed point)
    
    // square the fraction (mul64)
    frac *= frac;
    uint32_t fsql = (uint32_t)(frac);
    uint32_t fsqh = (uint32_t)(frac>>32);
    
    // renormalize the fraction (renorm)
    int s = C();
    while (fsqh || fsql & 0xFF000000) {
		int last_bit = fsqh & 0x00000001;
		fsqh >>= 1;
		fsql >>= 1;
		
		if (last_bit) {
			// assembly to avoid large shifts generated by gcc
			const unsigned int msb = 0x80000000;
			asm("or %[fsql], %[fsql], %[msb]"
				: [fsql]"+r"(fsql)
				: [msb]  "r"(msb));
		}
		
        exp += 0x01000000;
    }
	*c += C()-s;

    fsql &= ~0x00800000;
    fsql |= exp>>1;

    return fsql;
}

/*uint32_t float_square_bitlevel(uint32_t x) {
    if (x == 0)
        return x;

    uint32_t exp =  ((x<<1) & 0xFF000000) - 0x7F000000;
    uint64_t frac =  (x & 0x007FFFFF) | 0x00800000;

    exp *= 2;
    exp += 0x68000000; // 0x7F (bias) - 23 (squared fixed point)
    frac *= frac;

    while (frac & 0xFFFFFFFFFF000000) {
        frac >>= 1;
        exp += 0x01000000;
    }

    frac &= 0x007FFFFF;
    frac |= exp>>1;

    return frac;
}*/

float pow2f(float f) {
    int cdummy;
    return pow2fc(f, &cdummy);
}

float pow2fc(float f, int* c) {
    uint32_t fu = *(uint32_t*)&f;
    uint32_t fu_sq = float_square_bitlevel(fu, c);
    float f_sq = *(float*)&fu_sq;
    /*if (fabsf(f_sq - f*f) > 0.001f) {
		fogml_printf("failed on: ");
		fogml_printf_float(f);
		fogml_printf("\n");
	}*/
    return f_sq;
}
